const myName = "Gabriela";
const birthCity = "Belo Horizonte";
let birthYear = 1995;
console.log(myName);
console.log(birthCity);
console.log(birthYear);
birthYear = 2030;
console.log(birthYear);
birthCity = "Abaete";
console.log(birthCity);
